---
- name: Deploy EC2 Instance
  hosts: localhost
  become: 'yes'
  gather_facts: true
  vars:
    ansible_python_interpreter:/usr/bin/python3
    aws_region: us-east-1
    instance_type: t2.micro
    key_name: bjuatkey
    ami_id: i-03bf3ccbe6afc70f3  # Example AMI ID for Amazon Linux 2
    security_group: sg-0b52fa29523a310b5
    subnet_id: subnet-0ad59c546d76a1864
    instance_name: MyEC2Instance
  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_groups: [ "{{ security_group }}" ]
        wait: yes
        instance_tags:
          Name: "{{ instance_name }}"
      register: ec2

    - name: Display Instance ID and Public IP
      debug:
        msg:
          - "Instance ID: {{ ec2.instance_ids[0] }}"
          - "Public IP: {{ ec2.instances[0].public_ip_address }}"
