- hosts: servers
  gather_facts: true
  become: 'yes'
  tasks:
    - name: Installing httpd using yum
      yum: name=httpd state=present
    - name: start httpd service
      service: name=httpd state=started
      when: ansible_distribution != "Ubuntu"
    - name: Installing apache2 using apt
      apt: name=apache2 state=present
    - name: start apache2 service
      service: name=apache2 state=started
      when: ansible_distribution == "Ubuntu"
