- name: Install httpd using dnf
  hosts: servers
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Installing httpd using dnf
      dnf:
        name: httpd
        state: present
